### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by bomberstudios** [hite/sketch-measure-plus#5]
Hi there.

As you probably know, `[MSTextLayer lineSpacing]` has been deprecated for a while, and it will be removed in Sketch v40. Please update your Plugin to use `[MSTextLayer lineHeight]` instead, or it won't work in the next release :)

**Comment by bomberstudios** [comment]
BTW,  `setPatternImage:` is also deprecated, so use `setImage:` instead.

**Comment by hite** [comment]
@bomberstudios Thanks bomber for mentions.  I am afraid that I have no time to fix it until 7 Sep. As a result of HangZhou G20 Submit, i have a holiday to go back hometown where i have no workshop.
If I was back, I will fix it ASAP.

**Comment by hite** [comment]
replacing 2 matches of 'lineSpacing' with 'lineHeight'.
replacing 1 matches of 'setPatternImage' with 'setImage'.
Done on V1.2.0 @bomberstudios.
